version: '3'
services:
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - api1-networks
  mysqldb:
    image: mysql:8.1
    networks:
      - api1-networks
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: api1
        MYSQL_TCP_PORT: 9906
    ports:
      - "9906:9906"
    restart: always
  apigateway:
    build: apigateway
    restart: always
    ports:
      - "8585:8585"
    networks:
      - api1-networks
    environment:
      EUREKA_INSTANCE_HOSTNAME: apigateway
  api2:
    build: api2
    restart: always
    environment:
        MYSQL_HOST: mysqldb
        MYSQL_PORT: 9906
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
      - "9090:9090"
    networks:
      - api1-networks
    depends_on:
      - mysqldb
  api1:
    build: api1
    restart: always
    environment:
      API2_BASE_URL: http://api2:9090
      EUREKA_SERVICE_URL: http://apigateway:8585
      API1_HOST: api1
      REDIS_DB_HOST: redis-server
    ports:
      - "9595:9595"
    networks:
      - api1-networks
    depends_on:
      - api2
      - redis-server
networks:
  api1-networks: